### PR TITLE
First milestone completed

### PR DESCRIPTION
**Pull request by xtrmdarc**
I kindly request a code review for my completed milestone in which I created a base directory for my react calculator project and deployed it to Heroku.

- Linters config files added
- Deployed to Heroku successfully: https://xtrmdarc-react-calculator.herokuapp.com/
- Dependencies installed

Thank you

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## hello @xtrmdarc 

Great job...
We're also required in this setup phase to start editing the README with project-relevant information like names, project descriptions etc...

Even though you can enrich the README in later milestones

Please do so before you get thumbs up

**Comment by xtrmdarc** [comment]
Hi, Thank you for your review.
I just edited the README file following the example of my previous projects. However, I didn't read in the first milestone's specifications anything about editing the README file, this is why I didn't do it in the first place. Please let me know where in the specs I can find the README editing requirement. 

image

**Comment by shloch** [comment]
## hello @xtrmdarc , hello 

yeah you right......... at the stage the idea is that it's a reflex to always document a readme according to microverse

You very correct that it's not specified.. Thanks for updating though

**Review by fatymahmed — APPROVED** [review]
## Hi @xtrmdarc,
Good job implementing the changes 🎉🎉
- For your readme file, you could also add a `how to install locally` section, so please add this before merging/ 
## Status: Approved ✔️
_You may go ahead and merge this PR_

**Pull request merged**
